# This is a basic workflow to help you get started with Actions

name: vars

on:
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: "dupa"
  DAY_OF_WEEK: Monday
  
jobs:
  display-variables:
    runs-on: ubuntu-latest
    steps:
    - name: a
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ env.env_var }}
    - name: b
      run: |
        echo "env_var: $env_var"
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
