name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level' #⬅️ Opis
        required: true #⬅️ Czy wymagane
        default: 'warning' #⬅️ Domyślna wartość
        type: choice # ⬅️ Typ pola. To ma określoną listę możliwości
        options: #⬅️ Możliwe wartości
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      matrix:
        description: 'matrix parameter'
        type: string
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    strategy:
        matrix: ${{ fromJSON(inputs.matrix) }}
    steps:
      - name: Running for ${{ matrix.version }} and ${{ matrix.os }}
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
