name: matrix

on:
  workflow_dispatch:
  
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
        env:
          version: ${{ matrix.version }}
          os: ${{ matrix.os }}
