name: matrix

on:
  workflow_dispatch:
  
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
    - run: echo "Running Node version $version on $os"
      name: Running Node version ${{ matrix.version }} on ${{ matrix.os }}
      env:
        version: ${{ matrix.version }}
        os: ${{ matrix.os }}
