# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Cli_secret1
        env:
          secret : ${{secrets.CLI_SECRET1}}
        run: |
          echo "CLI_SECRET1: $secret"

      - name: Get Cli_secret2
        env:
          secret : ${{secrets.CLI_SECRET2}}
        run: |
          echo "CLI_SECRET2: $secret" >> some_secret.txt
      
      - uses: actions/upload-artifact@v4
        with:
          name: some_secret
          path: some_secret.txt
